  - plotly=4.5
  - dash=1.8
  - dash-leaflet=0.1.10
  - dask=2.30.0
  - dash-daq=0.3.2
  - dash-extensions=0.0.33
  - dash_bootstrap_components=0.10.7
  - jupyter-dash=0.3.1
  - pyproj=2.6.1
  - pandas=1.1.3
  - geopandas=0.8.1
