  - plotly=4.14
  - dash
  - dask
  - dash-daq
  - dash-bootstrap-components
  - jupyter-dash=0.3.1
  - pyproj=2.6.1
  - pandas=1.1.3
  - geopandas=0.8.1
  - pip
  - pip:
    - dash-leaflet
    - dash-extensions
